[[constraint]]
  branch = "master"
  name = "github.com/articulate/oktasdk-go"

[[constraint]]
  branch = "develop"
  name = "github.com/okta/okta-sdk-golang"

[[constraint]]
  version = "0.11.7"
  name = "github.com/hashicorp/terraform"

[prune]
  go-tests = true
  unused-packages = true
